# Don't change this! Version used to track needed updates.
version = 0
# WARNING: EXPERIMENTAL
# 
# In 1.21.1, Better Combats attacking with weapons in the offhand slot is incompatible with RPG Inventory
# 
# Setting this option to true, fixes the incompatibility. This may have unexpected consequences.
# Please report any issues you encounter when using this setting
# 
# Default: false
enable_experimental_swap_hand_attributes_algorithm = false
# When set to true, changing the players orientation and position while attacking is disabled.
# It is recommended to install Shoulder Surfing Reloaded, play in the third person perspective and activate the decoupled camera setting.
# Since the movement_multiplier setting in the Better Combat server config has no effect when this is set to true, it is recommended to set it to its default of 1.0.
# Use the item tag \"disables_movement_locking_during_attack\" and the entity type tag \"disables_movement_locking_when_ridden\" to control when the movement locking is applied.
# 
# Default: false
enable_movement_locking_attacks = false
# When set to true, jumping is disabled during attacks.
# Use the item tag \"disables_jump_restriction_during_attack\" and the entity type tag \"disables_jump_restriction_when_ridden\" to control when the jump restriction is applied.
# 
# Default: false
enable_jump_restriction_during_attacks = false
# When set to true, the pitch of the players attack is restricted.
# 
# Default: false
restrict_attack_pitch = false
# Only has an effect when 'restrict_attack_pitch' is set to 'true'.
# Describes the angle from 0, which means the final range is from -'attack_pitch_range' to 'attack_pitch_range'.
# 
# Default: 15.0
attack_pitch_range = 5.0
# Enables an alternative two_handed condition.
# If the offhand stack is empty and this is true, the mainhand stack is two_handed
# This is not active if the \"two_handed\" field in the weapon_attribute file is set to true.
# 
# Default: false
empty_offhand_equals_two_handing_mainhand = false
# Disables Better Combat's formerly client feature of continuously attacking while holding down the attack key.
# 
# Default: false
disable_better_combat_hold_to_attack = true
# When set to true, feinting an attack skips it.
# 
# Default: false
feinting_increases_combo_count = false
# 
# The stamina cost of all attacks is multiplied with this value when the attack is feinted.
# 
# Default: 1.0
global_feint_stamina_cost_multiplier = 1.0
# The stamina cost of all attacks is multiplied with this value when the attack is executed.
# 
# Default: 1.0
global_attack_stamina_cost_multiplier = 1.0