disabledMods = [
    "farmersdelight",
    "friendsandfoes",
    "harmonium",
    "minecraft",
    "mynethersdelight",
    "netherite_horse_armor",
    "sawmill",
    "sereneseasons",
    "supplementaries",
    "templates"
]