general = {disable_mod = false, hide_bossbar = true, shadow_text = true, auto_start = false, animationSpeed = 1.0, always_show_ping = false, hide_debug_crosshair = true, background_color = 1342177280, space_modules = false, always_show_profiler = false, animations = false, fontScale = 1.0, hide_sidebar = true, always_show_tps = false}
[[modules_right]]
	name = "system"
	name_color = 16777215
	value_color = 13421772
	lines = {opengl_version = true, allocation_rate = false, display = true, java_version = true, gpu_driver = true, memory_usage = true, allocated_memory = true, cpu = true, gpu_utilization = true, time = true, gpu = true}
	enabled = true
[[modules_right]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_right]]
	name = "target"
	name_color = 16777215
	value_color = 7324159
	lines = {id_fluid = true, fluid_tags = true, block_states = true, targeted_block = true, block_tags = true, id_block = true, nothing = true, nothing2 = true, targeted_fluid = true, targeted_entity = true, fluid_states = true}
	enabled = true

[[modules_left]]
	name = "minecraft"
	name_color = 16777215
	value_color = 13421772
	lines = {minecraft = true}
	enabled = true
[[modules_left]]
	color_high = 16777215
	color_med = 16777045
	name = "fps"
	lines = {fps = true}
	enabled = true
	color_low = 16740207
[[modules_left]]
	name = "server"
	name_color = 16777215
	value_color = 16777045
	lines = {server_tick = true, packets_sent = false, packets_received = false, tick_manager_status = false}
	enabled = true
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	color_x = 16740207
	color_y = 7339887
	color_z = 7324159
	name = "coords"
	name_color = 16777215
	lines = {chunk_coords = true, player_coords = true, block_coords = true, absolute_velocity = false, velocity = false, chunk_relative_coords = true, horizontal_velocity = false}
	enabled = true
[[modules_left]]
	name = "location"
	name_color = 16777215
	value_color = 13421772
	lines = {light = true, biome = true, rotation = false, facing = true, slime_chunk = true, local_difficulty = false, day_ticks = false, days_played = true, dimension = true, highest_block = false, highest_block_server = false, light_server = false}
	enabled = true
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	name = "entity"
	name_color = 16777215
	value_color = 13421772
	total_entities_color = 7339887
	lines = {entities = true, water_creature = true, underground_water_creature = true, ambient = true, particles = true, axolotls = true, creature = true, water_ambient = true, monster = true, misc = true}
	enabled = true
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	enabled_color = 7339887
	name = "help"
	name_color = 16777215
	value_color = 13421772
	disabled_color = 13421772
	lines = {help = true, fps_tps_new = true, ping = true, pie_graph_new = true}
	enabled = true
