#Align player to camera on left & right clicks
aimPlayerOnInteract = true
#How long player will be aligned to camera after left & right clicks
# Default: 40
# Range: 10 ~ 200
aimDuration = 50
#Angle in degrees within the player will slightly follow camera yaw (while standing still)
# Default: 45
# Range: 0 ~ 90
followYaw = 0
#Does camera should rotate freely during elytra flight
freeCameraDuringElytraFlight = true
#Completely remove third-person front view
skipThirdPersonFrontView = true
#How fast player changes movement direction in third-person
# Default: 50
# Range: 10 ~ 100
playerRotationSpeed = 45
#How fast player pitch follows camera pitch in third-person
# Default: 65
# Range: 10 ~ 100
pitchChangeSpeed = 90
