#Allowed Values: FIRST, MIDDLE, LAST
weaponCoolDownImportance = "MIDDLE"
disablePickaxesAndShovels = false
disableAxes = false
showBlockBreaking = true
showRangeWeaponDraw = true
showItemCooldowns = true
showFoodAndPotions = true
showSleep = true
showItemContainerFullness = false
