#Offset to horse model head pitch while riding. Lowers the head so it's not blocking the view. Default: 20
# Default: 20
# Range: 0 ~ 45
horse_model_head_offset = 0
#Offset to horse model head y position while riding. Lowers the head so it's not blocking the view. Default: true
# Default: 2
# Range: 0 ~ 4
horse_model_y_offset = 2
#If Lead slot is disabled, but lead is still required for hitching, indication of whether the Lead is equipped will be rendered in Horse inventory screen. Default: true
render_lead_indication_without_slot = true
