version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
arts_and_crafts = true
farmersdelight = true
supplementaries = true
toolsofsteel = true
metalfences = true
extshape = true
sawmill = true
templates = true
amendments = true
creeperoverhaul = true
ftbquests = true
snowrealmagic = true
friendsandfoes = true
bronze = true
minecraft = true
waterframes = true
